In [10]:
import pandas as pd
import sqlite3

In [11]:
# creating database connection
conn = sqlite3.connect('inventory.db')

In [13]:
# checking tables present in the database
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
tables

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [16]:
for table in tables['name']:
    print('_'*50, f'{table}','_'*50)
    print('Count of records:',pd.read_sql(f"select count(*) as count from {table}", conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5", conn))

__________________________________________________ begin_inventory __________________________________________________
Count of records: 750

,Item ID,Item Name,Category,Sub Category,Unit,SKU,Barcode,Quantity on Hand,Unit Cost ($),Total Value ($),...,ABC Classification,Min Order Qty,Max Stock Level,Annual Demand,Turnover Rate,Days on Hand,Stock Age (Days),Last Audit Date,Audited By,Notes
0,ITM-0001,Module B-1,Category G,Sub-Beta,Kg,SKU-22006,392316447751,432,236.07,101982.24,...,B,40,934,2869,6.64,55,171,2025-05-14,Auditor-6,OK
1,ITM-0002,Material C-2,Category H,Sub-Gamma,Each,SKU-19608,172713421809,300,721.69,216507.00,...,A,25,909,495,1.65,221,257,2025-10-10,Auditor-3,Check stock
2,ITM-0003,Equipment D-3,Category E,Sub-Beta,Kg,SKU-56971,106603480801,475,895.69,425452.75,...,B,20,275,4302,9.06,40,67,2025-07-24,Auditor-8,OK
3,ITM-0004,Tool E-4,Category B,Sub-Sigma,Carton,SKU-13771,301396937047,471,14.56,6857.76,...,A,19,686,519,1.10,332,76,2025-12-20,Auditor-6,Quality hold
4,ITM-0005,Material F-5,Category D,Sub-Alpha,Kg,SKU-51810,502935848802,484,391.76,189611.84,...,A,39,699,233,0.48,760,135,2025-04-17,Auditor-9,Fast moving

__________________________________________________ end_inventory __________________________________________________
Count of records: 750

,Item ID,Item Name,Category,Unit,SKU,Quantity on Hand,Unit Cost ($),Total Value ($),Reorder Level,Location/Bin,Supplier,Status,Notes
0,ITM-0001,Supply B-1,Category C,Roll,SKU-85164,241,57.68,13900.88,49,Bin B2,Delta Wholesale,Backordered,Pending review
1,ITM-0002,Supply C-2,Category E,Pack,SKU-71122,273,250.30,68331.90,44,Bin C3,Theta Co,Active,Check stock
2,ITM-0003,Supply D-3,Category F,Box,SKU-78680,27,399.77,10793.79,9,Bin D4,Epsilon Goods,Backordered,None
3,ITM-0004,Material E-4,Category G,Dozen,SKU-55740,110,451.73,49690.30,20,Bin E5,Theta Co,On Order,Returned
4,ITM-0005,Component F-5,Category F,Kg,SKU-30512,23,234.04,5382.92,46,Bin F6,Gamma Corp,On Order,Low stock

__________________________________________________ purchases __________________________________________________
Count of records: 699999

,purchase_id,order_number,customer_id,customer_name,customer_email,phone,product_id,product_name,category,sku,...,city,state,country,postal_code,shipping_address,notes,coupon_code,warehouse_id,agent_id,review_score
0,1,ORD-N1V2539D82HB,CUST-493653,Mary Smith,user887123@outlook.com,+1-977-606-3944,PROD-1432,Microphone,Accessories,SKU-OSOVFQPJUI,...,Sydney,State-FT,France,12120,4751 Elm Blvd,Fragile item,DEALJP93,WH-3,AGT-664,3.0
1,2,ORD-OFPRTVWSBX63,CUST-292492,James Garcia,user697736@gmail.com,+1-736-255-6455,PROD-2829,Earbuds,Audio,SKU-9ZSKIS8HKE,...,Dallas,State-O9,Brazil,53808,9411 Main St,None,DEALB1QS,WH-11,AGT-479,4.0
2,3,ORD-P8DVL9DENDDD,CUST-142396,Jennifer Jones,user298873@gmail.com,+1-855-276-7735,PROD-7899,Standing Desk,Accessories,SKU-WH7IE0400E,...,Austin,State-83,Canada,65761,5740 Pine Rd,Call before delivery,SUMMER20,WH-10,AGT-489,1.0
3,4,ORD-WWKY6QFFLNQB,CUST-641442,John Martinez,user909108@gmail.com,+1-317-621-2240,PROD-5781,Coffee Maker,Accessories,SKU-GUM4Y7MNWK,...,San Antonio,State-QU,Brazil,55987,932 Elm Blvd,Gift wrap requested,SAVE24,WH-9,AGT-155,NaN
4,5,ORD-WTE6DZ58Q8R0,CUST-165165,Linda Davis,user267472@outlook.com,+1-948-252-2603,PROD-9373,Mouse,Audio,SKU-3K2SC8RJQS,...,Jacksonville,State-72,Brazil,23298,1031 Oak Ave,Leave at door,DEALYBO3,WH-20,AGT-120,NaN

__________________________________________________ purchase_prices __________________________________________________
Count of records: 100

,Item ID,Item Name,SKU,Category,Supplier,Supplier Code,Supplier Contact,Supplier Email,Currency,Unit Cost ($),...,Net Price ($),Payment Terms,Lead Time (Days),Min Order Qty,Price Valid From,Price Valid Until,Last Updated,Updated By,Price Status,Notes
0,ITM-0001,Module B-1,SKU-29851,Category H,Zeta Imports,SUP-919,Contact-7,supplier61@email.com,EUR,387.21,...,360.63,Net 45,25,20,2025-04-09,2026-04-21,2025-08-12,User-4,Under Review,Fixed
1,ITM-0002,Component C-2,SKU-54533,Category B,Zeta Imports,SUP-730,Contact-28,supplier61@email.com,GBP,385.53,...,427.48,Net 15,26,32,2025-04-18,2026-04-10,2025-09-01,User-6,Expired,Contract rate
2,ITM-0003,Assembly D-3,SKU-76260,Category E,Theta Co,SUP-515,Contact-41,supplier6@email.com,EUR,934.10,...,956.74,Net 60,10,2,2025-05-21,2026-11-09,2025-12-23,User-2,Expired,Seasonal
3,ITM-0004,Widget E-4,SKU-56337,Category E,Theta Co,SUP-520,Contact-17,supplier82@email.com,GBP,961.66,...,1107.52,COD,10,25,2025-03-06,2026-05-27,2025-09-19,User-2,Expired,None
4,ITM-0005,Equipment F-5,SKU-47803,Category E,Delta Wholesale,SUP-209,Contact-28,supplier14@email.com,USD,909.83,...,967.77,Advance,11,30,2025-03-04,2026-11-04,2025-10-05,User-9,Active,None

__________________________________________________ sales __________________________________________________
Count of records: 500

,Sale ID,Date,Item ID,Item Name,SKU,Category,Customer Name,Customer ID,Customer Type,Region,...,Payment Status,Invoice No,Invoice Date,Due Date,Delivery Date,Return Qty,Return Amount ($),Warranty (Months),Sales Status,Notes
0,SALE-00001,2025-12-24,ITM-0065,Equipment N-65,SKU-23886,Category E,Prime Retail,CUST-7034,Wholesale,East,...,Partial,INV-605415,2025-12-24,2025-12-24,2025-12-25,0,0.0,12,Pending,Seasonal
1,SALE-00002,2025-04-01,ITM-0007,Assembly H-7,SKU-51464,Category F,Global Mart,CUST-4361,Government,South,...,Partial,INV-538071,2025-04-01,2025-05-01,2025-04-07,0,0.0,24,Returned,Promotional
2,SALE-00003,2025-02-14,ITM-0039,Tool N-39,SKU-49788,Category E,Quick Sales,CUST-4382,Retail,East,...,Paid,INV-608629,2025-02-14,2025-03-14,2025-02-17,0,0.0,24,Pending,Bulk order
3,SALE-00004,2025-10-12,ITM-0070,Assembly S-70,SKU-59671,Category H,Value Shop,CUST-6944,Retail,North,...,Unpaid,INV-527949,2025-10-12,2025-11-12,2025-10-14,0,0.0,24,Cancelled,Promotional
4,SALE-00005,2025-11-12,ITM-0062,Part K-62,SKU-82356,Category B,Sharma Traders,CUST-5543,Retail,South,...,Unpaid,INV-725024,2025-11-12,2025-12-12,2025-11-19,0,0.0,6,Cancelled,New customer

__________________________________________________ vendor_invoice __________________________________________________
Count of records: 300

,Invoice ID,Invoice No,Invoice Date,Due Date,Receipt Date,Vendor Name,Vendor ID,Vendor Contact,Vendor Email,Vendor Phone,...,Payment Date,Payment Reference,Amount Paid ($),Balance Due ($),Payment Status,PO Number,GRN Number,Invoice Status,Approved By,Remarks
0,VINV-00001,INV-507760,2025-08-11,2025-09-11,2025-08-15,Epsilon Goods,VND-2114,Contact-41,vendor96@email.com,+91-8091048706,...,2025-09-12,REF-126838,24277.96,24765.72,Under Review,PO-56037,GRN-80346,Pending,Manager-4,Quality issue
1,VINV-00002,INV-172750,2025-01-08,2025-02-08,2025-01-10,Beta Traders,VND-1568,Contact-36,vendor79@email.com,+91-8262208387,...,2025-02-18,REF-446066,56376.65,59647.85,Paid,PO-12653,GRN-98929,On Hold,Manager-5,Partial shipment
2,VINV-00003,INV-722016,2025-04-11,2025-05-11,2025-04-15,Beta Traders,VND-5532,Contact-40,vendor36@email.com,+91-7248463367,...,None,None,0.00,73986.73,Overdue,PO-94594,GRN-27660,Pending,Manager-4,Partial shipment
3,VINV-00004,INV-512146,2025-12-20,2025-12-20,2025-12-22,Theta Co,VND-2116,Contact-9,vendor36@email.com,+91-9766648846,...,2025-12-02,REF-828274,5512.73,0.00,Partial,PO-41730,GRN-11279,Pending,Manager-3,Quality issue
4,VINV-00005,INV-743380,2025-09-01,2025-10-01,2025-09-06,Delta Wholesale,VND-6110,Contact-48,vendor57@email.com,+91-7822007220,...,None,None,0.00,55507.64,Unpaid,PO-58595,GRN-28828,On Hold,Manager-4,Partial shipment

In [20]:
purchases = pd.read_sql_query("select * from purchases where customer_id = 'CUST-142396' ", conn)
purchases

,purchase_id,order_number,customer_id,customer_name,customer_email,phone,product_id,product_name,category,sku,...,city,state,country,postal_code,shipping_address,notes,coupon_code,warehouse_id,agent_id,review_score
0,3,ORD-P8DVL9DENDDD,CUST-142396,Jennifer Jones,user298873@gmail.com,+1-855-276-7735,PROD-7899,Standing Desk,Accessories,SKU-WH7IE0400E,...,Austin,State-83,Canada,65761,5740 Pine Rd,Call before delivery,SUMMER20,WH-10,AGT-489,1.0
1,353031,ORD-ZY6G918WE5VG,CUST-142396,Robert Miller,user491669@outlook.com,+1-528-950-3948,PROD-5221,USB Hub,Computers,SKU-DU6G5RCI5A,...,Phoenix,State-5V,UK,79180,8301 Main St,Leave at door,None,WH-19,AGT-498,1.0

In [34]:
purchase_prices = pd.read_sql_query('select * from purchase_prices where "Supplier_Email" = "supplier61@email.com"', conn)
purchase_prices

Empty DataFrame
Columns: [Item ID, Item Name, SKU, Category, Supplier, Supplier Code, Supplier Contact, Supplier Email, Currency, Unit Cost ($), Last Purchase Price ($), Avg Purchase Price ($), Min Price ($), Max Price ($), Bulk Price (50+) ($), Bulk Price (100+) ($), Bulk Price (500+) ($), Tax Rate (%), Discount (%), Net Price ($), Payment Terms, Lead Time (Days), Min Order Qty, Price Valid From, Price Valid Until, Last Updated, Updated By, Price Status, Notes]
Index: []

[0 rows x 29 columns]

In [36]:
vendor_invoice = pd.read_sql_query("""select * from vendor_invoice where 'Vendor Contact' = 'Contact-40'""", conn)
vendor_invoice

Empty DataFrame
Columns: [Invoice ID, Invoice No, Invoice Date, Due Date, Receipt Date, Vendor Name, Vendor ID, Vendor Contact, Vendor Email, Vendor Phone, Vendor Address, Vendor City, Vendor State, Vendor GST No, Item ID, Item Name, SKU, Category, Unit, Quantity, Unit Price ($), Total Amount ($), Discount (%), Discount Amount ($), Tax Rate (%), Tax Amount ($), Net Payable ($), Currency, Exchange Rate, Amount (INR), Payment Mode, Payment Date, Payment Reference, Amount Paid ($), Balance Due ($), Payment Status, PO Number, GRN Number, Invoice Status, Approved By, Remarks]
Index: []

[0 rows x 41 columns]

In [37]:
sales = pd.read_sql_query("""select * from sales where 'Customer Type' = 'Retail'""", conn)
sales

Empty DataFrame
Columns: [Sale ID, Date, Item ID, Item Name, SKU, Category, Customer Name, Customer ID, Customer Type, Region, City, Sales Rep, Channel, Quantity Sold, Unit Price ($), Total Sale ($), Cost Price ($), Gross Profit ($), Profit Margin (%), Discount (%), Discount Amount ($), Net Revenue ($), Tax Rate (%), Tax Amount ($), Invoice Amount ($), Payment Mode, Payment Status, Invoice No, Invoice Date, Due Date, Delivery Date, Return Qty, Return Amount ($), Warranty (Months), Sales Status, Notes]
Index: []

[0 rows x 36 columns]

In [44]:
purchases.groupby(['order_number', 'customer_name'])[['category','city']].sum()

                                    category     city
order_number     customer_name
ORD-P8DVL9DENDDD Jennifer Jones  Accessories   Austin
ORD-ZY6G918WE5VG Robert Miller     Computers  Phoenix

In [45]:
purchase_prices

Empty DataFrame
Columns: [Item ID, Item Name, SKU, Category, Supplier, Supplier Code, Supplier Contact, Supplier Email, Currency, Unit Cost ($), Last Purchase Price ($), Avg Purchase Price ($), Min Price ($), Max Price ($), Bulk Price (50+) ($), Bulk Price (100+) ($), Bulk Price (500+) ($), Tax Rate (%), Discount (%), Net Price ($), Payment Terms, Lead Time (Days), Min Order Qty, Price Valid From, Price Valid Until, Last Updated, Updated By, Price Status, Notes]
Index: []

[0 rows x 29 columns]

In [49]:
vendor_invoice.columns

Index(['Invoice ID', 'Invoice No', 'Invoice Date', 'Due Date', 'Receipt Date',
       'Vendor Name', 'Vendor ID', 'Vendor Contact', 'Vendor Email',
       'Vendor Phone', 'Vendor Address', 'Vendor City', 'Vendor State',
       'Vendor GST No', 'Item ID', 'Item Name', 'SKU', 'Category', 'Unit',
       'Quantity', 'Unit Price ($)', 'Total Amount ($)', 'Discount (%)',
       'Discount Amount ($)', 'Tax Rate (%)', 'Tax Amount ($)',
       'Net Payable ($)', 'Currency', 'Exchange Rate', 'Amount (INR)',
       'Payment Mode', 'Payment Date', 'Payment Reference', 'Amount Paid ($)',
       'Balance Due ($)', 'Payment Status', 'PO Number', 'GRN Number',
       'Invoice Status', 'Approved By', 'Remarks'],
      dtype='object')

In [52]:
purchases

,purchase_id,order_number,customer_id,customer_name,customer_email,phone,product_id,product_name,category,sku,...,city,state,country,postal_code,shipping_address,notes,coupon_code,warehouse_id,agent_id,review_score
0,3,ORD-P8DVL9DENDDD,CUST-142396,Jennifer Jones,user298873@gmail.com,+1-855-276-7735,PROD-7899,Standing Desk,Accessories,SKU-WH7IE0400E,...,Austin,State-83,Canada,65761,5740 Pine Rd,Call before delivery,SUMMER20,WH-10,AGT-489,1.0
1,353031,ORD-ZY6G918WE5VG,CUST-142396,Robert Miller,user491669@outlook.com,+1-528-950-3948,PROD-5221,USB Hub,Computers,SKU-DU6G5RCI5A,...,Phoenix,State-5V,UK,79180,8301 Main St,Leave at door,None,WH-19,AGT-498,1.0

In [56]:
sales.groupby('Sale ID')[['Payment Status','Return Amount ($)','Sales Status']].sum()

Empty DataFrame
Columns: [Payment Status, Return Amount ($), Sales Status]
Index: []

In [57]:
vendor_invoice.columns

Index(['Invoice ID', 'Invoice No', 'Invoice Date', 'Due Date', 'Receipt Date',
       'Vendor Name', 'Vendor ID', 'Vendor Contact', 'Vendor Email',
       'Vendor Phone', 'Vendor Address', 'Vendor City', 'Vendor State',
       'Vendor GST No', 'Item ID', 'Item Name', 'SKU', 'Category', 'Unit',
       'Quantity', 'Unit Price ($)', 'Total Amount ($)', 'Discount (%)',
       'Discount Amount ($)', 'Tax Rate (%)', 'Tax Amount ($)',
       'Net Payable ($)', 'Currency', 'Exchange Rate', 'Amount (INR)',
       'Payment Mode', 'Payment Date', 'Payment Reference', 'Amount Paid ($)',
       'Balance Due ($)', 'Payment Status', 'PO Number', 'GRN Number',
       'Invoice Status', 'Approved By', 'Remarks'],
      dtype='object')

In [63]:
Amount_Paid_summary = pd.read_sql_query("""select "Invoice ID", SUM("Total Amount ($)") AS total_Amount
From vendor_invoice
GROUP BY "Invoice ID"
""", conn)

Amount_Paid_summary

     Invoice ID  total_Amount
0    VINV-00001      47772.92
1    VINV-00002     120632.66
2    VINV-00003      75410.48
3    VINV-00004       6007.12
4    VINV-00005      46629.40
..          ...           ...
295  VINV-00296      68840.10
296  VINV-00297      12976.00
297  VINV-00298       8396.76
298  VINV-00299     130713.00
299  VINV-00300       7443.92

[300 rows x 2 columns]

In [65]:
pd.read_sql_query("""SELECT
    "Vendor ID",
    "Vendor Name",
    "Category",
    SUM("Quantity") AS total_quantity,
    SUM("Total Amount ($)") AS total_purchase_amount,
    SUM("Amount Paid ($)") AS total_paid_amount,
    SUM("Balance Due ($)") AS total_due_amount
    FROM vendor_invoice
    WHERE "Unit Price ($)" > 0
    GROUP BY "Vendor ID", "Vendor Name", "Category"
    ORDER BY total_purchase_amount DESC""", conn)

,Vendor ID,Vendor Name,Category,total_quantity,total_purchase_amount,total_paid_amount,total_due_amount
0,VND-1340,Delta Wholesale,Category C,194,193546.04,0.00,193468.62
1,VND-7663,Alpha Supplies,Category G,199,192214.10,188585.10,0.00
2,VND-1945,Zeta Imports,Category G,198,170337.42,0.00,185054.58
3,VND-3456,Theta Co,Category B,192,169860.48,0.00,153919.07
4,VND-4269,Zeta Imports,Category A,174,168353.70,165175.18,0.00
...,...,...,...,...,...,...,...
295,VND-7556,Beta Traders,Category G,31,1414.22,476.89,1033.36
296,VND-8573,Beta Traders,Category H,139,977.17,0.00,977.32
297,VND-3014,Alpha Supplies,Category D,3,867.09,0.00,984.29
298,VND-5383,Eta Distributors,Category E,1,698.30,0.00,712.76
299,VND-2165,Beta Traders,Category H,31,643.56,243.91,448.77

In [67]:
sales.columns

Index(['Sale ID', 'Date', 'Item ID', 'Item Name', 'SKU', 'Category',
       'Customer Name', 'Customer ID', 'Customer Type', 'Region', 'City',
       'Sales Rep', 'Channel', 'Quantity Sold', 'Unit Price ($)',
       'Total Sale ($)', 'Cost Price ($)', 'Gross Profit ($)',
       'Profit Margin (%)', 'Discount (%)', 'Discount Amount ($)',
       'Net Revenue ($)', 'Tax Rate (%)', 'Tax Amount ($)',
       'Invoice Amount ($)', 'Payment Mode', 'Payment Status', 'Invoice No',
       'Invoice Date', 'Due Date', 'Delivery Date', 'Return Qty',
       'Return Amount ($)', 'Warranty (Months)', 'Sales Status', 'Notes'],
      dtype='object')

In [68]:
pd.read_sql_query("""SELECT
    "Customer Type",
    "Category",
    SUM("Total Sale ($)") AS total_sales_dollars,
    SUM("Gross Profit ($)") AS total_profit,
    SUM("Tax Amount ($)") AS total_tax
    FROM sales
    GROUP BY "Customer Type", "Category"
    ORDER BY total_sales_dollars DESC""", conn)

   Customer Type    Category  total_sales_dollars  total_profit  total_tax
0      Wholesale  Category A           1654920.98     268491.54  277753.02
1      Corporate  Category G           1282032.27     305074.59  121247.05
2     Government  Category E           1161299.66     217421.90  158719.98
3      Corporate  Category A           1157539.13     288005.65  198912.38
4         Retail  Category G           1118803.85     193888.93  180315.73
5     Government  Category C           1069943.07     278706.21  192607.16
6         Retail  Category A            987105.81     146813.12  142668.53
7      Wholesale  Category G            980822.40     229692.48  139746.51
8     Government  Category B            963206.47     179407.99  121275.56
9      Corporate  Category H            948748.56     127356.40   93519.79
10    Government  Category A            948376.04     146104.05  125425.15
11    Government  Category H            932465.05     244641.39  135116.30
12        Retail  Category C            824948.60     144631.73  109517.45
13     Corporate  Category C            811315.65      94264.15  115424.95
14     Wholesale  Category E            792585.63     160950.65   64129.47
15    Government  Category G            789340.44     225910.25   85862.73
16        Retail  Category F            773108.29     146507.84   84169.74
17     Corporate  Category D            694348.53     116606.37   78371.94
18        Retail  Category E            670954.20     120871.09   74690.67
19     Wholesale  Category B            661385.10     160169.90  111873.24
20     Corporate  Category F            647504.62     120937.24   83465.11
21     Wholesale  Category H            640309.33     124131.94  137489.65
22     Wholesale  Category F            617097.40     115169.46   80963.29
23    Government  Category D            611939.62     103325.60   73845.38
24    Government  Category F            595969.42     143974.76   68551.63
25     Wholesale  Category D            591479.28      89817.10   72506.70
26     Corporate  Category E            566467.52     157678.81   72885.55
27        Retail  Category H            546708.55     114572.49   71626.46
28        Retail  Category D            522634.96     117769.20   88653.27
29        Retail  Category B            428475.25      78329.42   62399.21
30     Wholesale  Category C            380187.18      73134.87   59600.78
31     Corporate  Category B            320697.51      61416.29   53334.44

In [71]:
purchase_prices.columns

Index(['Item ID', 'Item Name', 'SKU', 'Category', 'Supplier', 'Supplier Code',
       'Supplier Contact', 'Supplier Email', 'Currency', 'Unit Cost ($)',
       'Last Purchase Price ($)', 'Avg Purchase Price ($)', 'Min Price ($)',
       'Max Price ($)', 'Bulk Price (50+) ($)', 'Bulk Price (100+) ($)',
       'Bulk Price (500+) ($)', 'Tax Rate (%)', 'Discount (%)',
       'Net Price ($)', 'Payment Terms', 'Lead Time (Days)', 'Min Order Qty',
       'Price Valid From', 'Price Valid Until', 'Last Updated', 'Updated By',
       'Price Status', 'Notes'],
      dtype='object')

In [72]:
sales['SKU'].nunique()
vendor_invoice['SKU'].nunique()
purchase_prices['SKU'].nunique()

0

In [73]:
set(sales.columns).intersection(set(vendor_invoice.columns))

{'Category',
 'Discount (%)',
 'Discount Amount ($)',
 'Due Date',
 'Invoice Date',
 'Invoice No',
 'Item ID',
 'Item Name',
 'Payment Mode',
 'Payment Status',
 'SKU',
 'Tax Amount ($)',
 'Tax Rate (%)',
 'Unit Price ($)'}

In [74]:
set(sales.columns).intersection(set(purchase_prices.columns))

{'Category',
 'Discount (%)',
 'Item ID',
 'Item Name',
 'Notes',
 'SKU',
 'Tax Rate (%)'}

In [99]:
import time
start = time.time()
vendor_sales_summary = pd.read_sql_query("""
SELECT

    pp.[Item ID],
    pp.[Item Name],
    pp.[Category],
    vi.[vendor Name] AS VendorName,
    pp.[Supplier],
    

    pp.[Avg Purchase Price ($)] AS AvgPurchasePrice,
    pp.[Net Price ($)] AS NetPurchasePrice,

    SUM(s.[Quantity Sold]) AS TotalSalesQuantity,
    SUM(s.[Total Sale ($)]) AS TotalSalesAmount,
    SUM(s.[Net Revenue ($)]) AS TotalNetRevenue,
    SUM(s.[Gross Profit ($)]) AS TotalGrossProfit,

    SUM(vi.[Quantity]) AS TotalPurchaseQuantity,
    SUM(vi.[Total Amount ($)]) AS TotalPurchaseAmount,
    SUM(vi.[Amount Paid ($)]) AS TotalAmountPaid,
    SUM(vi.[Balance Due ($)]) AS TotalBalanceDue

FROM purchase_prices pp

JOIN sales s
    ON pp.[Item ID] = s.[Item ID]

JOIN vendor_invoice vi
    ON pp.[Item ID] = vi.[Item ID]

GROUP BY

    pp.[Item ID],
    pp.[Item Name],
    pp.[Category],
    pp.[Supplier],
    pp.[Avg Purchase Price ($)],
    pp.[Net Price ($)]

ORDER BY TotalSalesAmount DESC

""", conn)
end = time.time()

In [82]:
vendor_sales_summary

,Item ID,Item Name,Category,Supplier,AvgPurchasePrice,NetPurchasePrice,TotalSalesQuantity,TotalSalesAmount,TotalNetRevenue,TotalGrossProfit,TotalPurchaseQuantity,TotalPurchaseAmount,TotalAmountPaid,TotalBalanceDue
0,ITM-0011,Component L-11,Category G,Eta Distributors,678.71,828.30,2290,2296211.10,1920726.30,349344.85,3896,1765311.52,1182596.96,752283.76
1,ITM-0005,Equipment F-5,Category E,Delta Wholesale,897.21,967.77,1625,2204478.85,1791704.65,473668.05,2220,560869.45,128752.80,428503.95
2,ITM-0027,Supply B-27,Category G,Beta Traders,650.52,662.15,1776,2182374.57,1923634.20,604622.40,4600,1552671.60,1489975.70,62281.50
3,ITM-0051,Material Z-51,Category H,Theta Co,175.79,195.53,1404,2136352.00,1856537.16,362793.08,3409,2810580.50,2900725.87,0.00
4,ITM-0006,Product G-6,Category E,Delta Wholesale,533.46,541.71,1794,2072823.90,1863706.80,366426.84,2904,2021479.08,1048851.96,1175141.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,ITM-0072,Equipment U-72,Category B,Delta Wholesale,225.31,253.96,178,152310.75,127305.47,25685.82,380,312648.80,311998.48,0.00
90,ITM-0079,Material B-79,Category F,Zeta Imports,466.67,435.65,254,110128.84,88316.74,22049.52,684,327393.00,135645.36,237298.20
91,ITM-0035,Equipment J-35,Category F,Delta Wholesale,848.37,921.74,78,54885.32,48944.40,6626.22,490,446951.68,329531.16,154186.94
92,ITM-0076,Part Y-76,Category G,Beta Traders,327.17,344.32,199,48692.93,41764.31,3467.82,96,64445.76,67126.71,0.00
93,ITM-0059,Assembly H-59,Category G,Epsilon Goods,763.99,749.03,111,34931.76,30737.49,7409.34,534,318409.34,292684.18,61205.66

In [83]:
vendor_sales_summary.dtypes

Item ID                   object
Item Name                 object
Category                  object
Supplier                  object
AvgPurchasePrice         float64
NetPurchasePrice         float64
TotalSalesQuantity         int64
TotalSalesAmount         float64
TotalNetRevenue          float64
TotalGrossProfit         float64
TotalPurchaseQuantity      int64
TotalPurchaseAmount      float64
TotalAmountPaid          float64
TotalBalanceDue          float64
dtype: object

In [84]:
vendor_sales_summary.isnull().sum()

Item ID                  0
Item Name                0
Category                 0
Supplier                 0
AvgPurchasePrice         0
NetPurchasePrice         0
TotalSalesQuantity       0
TotalSalesAmount         0
TotalNetRevenue          0
TotalGrossProfit         0
TotalPurchaseQuantity    0
TotalPurchaseAmount      0
TotalAmountPaid          0
TotalBalanceDue          0
dtype: int64

In [87]:
vendor_invoice.columns

Index(['Invoice ID', 'Invoice No', 'Invoice Date', 'Due Date', 'Receipt Date',
       'Vendor Name', 'Vendor ID', 'Vendor Contact', 'Vendor Email',
       'Vendor Phone', 'Vendor Address', 'Vendor City', 'Vendor State',
       'Vendor GST No', 'Item ID', 'Item Name', 'SKU', 'Category', 'Unit',
       'Quantity', 'Unit Price ($)', 'Total Amount ($)', 'Discount (%)',
       'Discount Amount ($)', 'Tax Rate (%)', 'Tax Amount ($)',
       'Net Payable ($)', 'Currency', 'Exchange Rate', 'Amount (INR)',
       'Payment Mode', 'Payment Date', 'Payment Reference', 'Amount Paid ($)',
       'Balance Due ($)', 'Payment Status', 'PO Number', 'GRN Number',
       'Invoice Status', 'Approved By', 'Remarks'],
      dtype='object')

In [92]:
vendor_sales_summary.columns

Index(['Item ID', 'Item Name', 'Category', 'VendorName', 'Supplier',
       'AvgPurchasePrice', 'NetPurchasePrice', 'TotalSalesQuantity',
       'TotalSalesAmount', 'TotalNetRevenue', 'TotalGrossProfit',
       'TotalPurchaseQuantity', 'TotalPurchaseAmount', 'TotalAmountPaid',
       'TotalBalanceDue'],
      dtype='object')

In [93]:
vendor_sales_summary['VendorName'].unique()

array(['Beta Traders', 'Alpha Supplies', 'Epsilon Goods',
       'Delta Wholesale', 'Gamma Corp', 'Eta Distributors', 'Theta Co'],
      dtype=object)

In [100]:
vendor_sales_summary['NetPurchasePrice'] = vendor_sales_summary['NetPurchasePrice'].astype('float64')

In [101]:
vendor_sales_summary.fillna(0, inplace = True)

In [105]:
vendor_sales_summary['NetPurchasePrice'].dtype

dtype('float64')

In [108]:
vendor_sales_summary['TotalGrossProfit'] = vendor_sales_summary['TotalSalesAmount'] - vendor_sales_summary['TotalPurchaseAmount']

In [110]:
vendor_sales_summary['TotalGrossProfit'].min()

-2637691.66

In [111]:
vendor_sales_summary['TotalBalanceDue'] = (vendor_sales_summary['TotalGrossProfit'] / vendor_sales_summary['TotalSalesAmount'])*100

In [113]:
vendor_sales_summary['StockTurnover'] = (vendor_sales_summary['TotalSalesQuantity'] /vendor_sales_summary['TotalPurchaseQuantity'])

In [115]:
vendor_sales_summary['SalestoPurchaseRatio'] = (vendor_sales_summary['TotalSalesAmount'] /vendor_sales_summary['TotalPurchaseAmount'])

In [117]:
vendor_sales_summary.columns

Index(['Item ID', 'Item Name', 'Category', 'VendorName', 'Supplier',
       'AvgPurchasePrice', 'NetPurchasePrice', 'TotalSalesQuantity',
       'TotalSalesAmount', 'TotalNetRevenue', 'TotalGrossProfit',
       'TotalPurchaseQuantity', 'TotalPurchaseAmount', 'TotalAmountPaid',
       'TotalBalanceDue', 'StockTurnover', 'SalestoPurchaseRatio'],
      dtype='object')

In [116]:
cursor = conn.cursor()

In [126]:
pd.read_sql_query("select * from vendor_sales_summary",conn)

Empty DataFrame
Columns: [ItemID, ItemName, Category, VendorName, Supplier, AvgPurchasePrice, NetPurchasePrice, TotalSalesQuantity, TotalSalesAmount, TotalNetRevenue, TotalGrossProfit, TotalPurchaseQuantity, TotalPurchaseAmount, TotalAmountPaid, TotalBalanceDue, StockTurnover, SalestoPurchaseRatio]
Index: []

In [128]:
vendor_sales_summary.to_sql('vendor_sales_summary', conn, if_exists = 'replace', index = False)

94

In [129]:
vendor_sales_summary.columns

Index(['Item ID', 'Item Name', 'Category', 'VendorName', 'Supplier',
       'AvgPurchasePrice', 'NetPurchasePrice', 'TotalSalesQuantity',
       'TotalSalesAmount', 'TotalNetRevenue', 'TotalGrossProfit',
       'TotalPurchaseQuantity', 'TotalPurchaseAmount', 'TotalAmountPaid',
       'TotalBalanceDue', 'StockTurnover', 'SalestoPurchaseRatio'],
      dtype='object')

In [130]:
pd.read_sql_query(
    "PRAGMA table_info(vendor_invoice)",
    conn
)

    cid                 name    type  notnull dflt_value  pk
0     0           Invoice ID    TEXT        0       None   0
1     1           Invoice No    TEXT        0       None   0
2     2         Invoice Date    TEXT        0       None   0
3     3             Due Date    TEXT        0       None   0
4     4         Receipt Date    TEXT        0       None   0
5     5          Vendor Name    TEXT        0       None   0
6     6            Vendor ID    TEXT        0       None   0
7     7       Vendor Contact    TEXT        0       None   0
8     8         Vendor Email    TEXT        0       None   0
9     9         Vendor Phone    TEXT        0       None   0
10   10       Vendor Address    TEXT        0       None   0
11   11          Vendor City    TEXT        0       None   0
12   12         Vendor State    TEXT        0       None   0
13   13        Vendor GST No    TEXT        0       None   0
14   14              Item ID    TEXT        0       None   0
15   15            Item Name    TEXT        0       None   0
16   16                  SKU    TEXT        0       None   0
17   17             Category    TEXT        0       None   0
18   18                 Unit    TEXT        0       None   0
19   19             Quantity  BIGINT        0       None   0
20   20       Unit Price ($)   FLOAT        0       None   0
21   21     Total Amount ($)   FLOAT        0       None   0
22   22         Discount (%)   FLOAT        0       None   0
23   23  Discount Amount ($)   FLOAT        0       None   0
24   24         Tax Rate (%)   FLOAT        0       None   0
25   25       Tax Amount ($)   FLOAT        0       None   0
26   26      Net Payable ($)   FLOAT        0       None   0
27   27             Currency    TEXT        0       None   0
28   28        Exchange Rate   FLOAT        0       None   0
29   29         Amount (INR)   FLOAT        0       None   0
30   30         Payment Mode    TEXT        0       None   0
31   31         Payment Date    TEXT        0       None   0
32   32    Payment Reference    TEXT        0       None   0
33   33      Amount Paid ($)   FLOAT        0       None   0
34   34      Balance Due ($)   FLOAT        0       None   0
35   35       Payment Status    TEXT        0       None   0
36   36            PO Number    TEXT        0       None   0
37   37           GRN Number    TEXT        0       None   0
38   38       Invoice Status    TEXT        0       None   0
39   39          Approved By    TEXT        0       None   0
40   40              Remarks    TEXT        0       None   0

In [148]:
import pandas as pd
import sqlite3
import logging
from ingestion_db import ingest_db

logging.basicConfig(
    filename="logs/get_vendor_summary.log",
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s - %(message)s",
    filemode="a"
)


def create_vendor_summary(conn):
    """
    This function merges different tables
    and creates vendor sales summary.
    """

    query = """
    SELECT

        pp.[Item ID],
        pp.[Item Name],
        pp.[Category],
        vi.[Vendor Name] AS VendorName,
        pp.[Supplier],

        pp.[Avg Purchase Price ($)] AS AvgPurchasePrice,
        pp.[Net Price ($)] AS NetPurchasePrice,

        SUM(s.[Quantity Sold]) AS TotalSalesQuantity,
        SUM(s.[Total Sale ($)]) AS TotalSalesAmount,
        SUM(s.[Net Revenue ($)]) AS TotalNetRevenue,
        SUM(s.[Gross Profit ($)]) AS TotalGrossProfit,

        SUM(vi.[Quantity]) AS TotalPurchaseQuantity,
        SUM(vi.[Total Amount ($)]) AS TotalPurchaseAmount,
        SUM(vi.[Amount Paid ($)]) AS TotalAmountPaid,
        SUM(vi.[Balance Due ($)]) AS TotalBalanceDue

    FROM purchase_prices pp

    JOIN sales s
        ON pp.[Item ID] = s.[Item ID]

    JOIN vendor_invoice vi
        ON pp.[Item ID] = vi.[Item ID]

    GROUP BY
        pp.[Item ID],
        pp.[Item Name],
        pp.[Category],
        vi.[Vendor Name],
        pp.[Supplier],
        pp.[Avg Purchase Price ($)],
        pp.[Net Price ($)]

    ORDER BY TotalSalesAmount DESC
    """

    vendor_sales_summary = pd.read_sql_query(query, conn)

    return vendor_sales_summary


def clean_data(df):
    """
    This function cleans data.
    """

    # datatype conversion
    df["NetPurchasePrice"] = df["NetPurchasePrice"].astype("float64")

    # fill null values
    df.fillna(0, inplace=True)

    # remove extra spaces
    df["VendorName"] = df["VendorName"].astype(str).str.strip()

    # calculated columns
    df["TotalGrossProfit"] = (
        df["TotalSalesAmount"]
        - df["TotalPurchaseAmount"]
    )

    df["TotalBalanceDuePercent"] = (
        df["TotalGrossProfit"]
        / df["TotalSalesAmount"]
    ) * 100

    df["StockTurnover"] = (
        df["TotalSalesQuantity"]
        / df["TotalPurchaseQuantity"]
    )

    df["SalestoPurchaseRatio"] = (
        df["TotalSalesAmount"]
        / df["TotalPurchaseAmount"]
    )

    return df


if __name__ == "__main__":

    conn = sqlite3.connect("inventory.db")

    logging.info("Creating Vendor Summary Table....")
    summary_df = create_vendor_summary(conn)
    logging.info(summary_df.head())

    logging.info("Cleaning Data.....")
    clean_df = clean_data(summary_df)
    logging.info(clean_df.head())

    logging.info("Ingesting Data.....")
    ingest_db(clean_df, "vendor_sales_summary", conn)

    logging.info("Completed")

    conn.close()

In [147]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("inventory.db")

cols = pd.read_sql_query(
    "PRAGMA table_info(vendor_invoice)",
    conn
)

print(cols["name"])

0              Invoice ID
1              Invoice No
2            Invoice Date
3                Due Date
4            Receipt Date
5             Vendor Name
6               Vendor ID
7          Vendor Contact
8            Vendor Email
9            Vendor Phone
10         Vendor Address
11            Vendor City
12           Vendor State
13          Vendor GST No
14                Item ID
15              Item Name
16                    SKU
17               Category
18                   Unit
19               Quantity
20         Unit Price ($)
21       Total Amount ($)
22           Discount (%)
23    Discount Amount ($)
24           Tax Rate (%)
25         Tax Amount ($)
26        Net Payable ($)
27               Currency
28          Exchange Rate
29           Amount (INR)
30           Payment Mode
31           Payment Date
32      Payment Reference
33        Amount Paid ($)
34        Balance Due ($)
35         Payment Status
36              PO Number
37             GRN Number
38         Invoice Status
39            Approved By
40                Remarks
Name: name, dtype: object

In [1]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1'])